### PR TITLE
docs: specify all peer deps in install instructions

### PR DESCRIPTION
**Pull request by EricCrosson**

### CODE REVIEW

**Comment by EricCrosson** [comment]
Cheers

**Comment by mrgrain** [comment]
Thank you!

**Comment by mrgrain** [comment]
@EricCrosson Thanks for the PR!

It occurred to me that with npm 7, peer dependencies don't have to be installed manually any more. I have adjusted the docs a bit. What do you think? Is this still clear enough?

**Comment by EricCrosson** [comment]
Brilliant :+1: Good thinking

**Pull request merged**
